### ISSUE TITLE
当前用户没有足够的权限访问此接口

### ISSUE THREAD

**Issue by somuc** [xkrfer/pushdeer-node#1]
可是我按图片的步骤在GitHub上申请了、也在Google cloud上申请了，并配置进docker-compose.yml，然后npm run start了。。网页也能正常访问
![image](https://user-images.githubusercontent.com/37100931/170442176-893cf1ff-a777-4233-a932-ae5ed98c4595.png)

**Comment by xkrfer** [comment]
你是在本地启动pushdeer-crx测试，还是直接装在浏览器里安装扩展使用？
1. 在本地的话无法通过github登录自动登录，需要在登录成功页打开控制台查看登录成功后得到token再填入pushdeer-crx项目中进行使用。
<img width="722" alt="image" src="https://user-images.githubusercontent.com/97657327/170705510-a75c39f2-827d-476b-ba87-d5234f0687a3.png">
2. 已经使用浏览器插件的话，请检查endpoint是否填入正确，上图的错误提示只有未登录或token失效的情况才会出现。

**Comment by xkrfer** [comment]
新增 [Railway部署方式](https://github.com/xkrfer/pushdeer-node/wiki/Railway%E9%83%A8%E7%BD%B2pushdeer-node)，可以尝试一下。

**Comment by YoshiokaHikari** [comment]
我也遇到了一样的问题，Github 登录显示 {"statusCode":500,"message":"Internal server error"}。

**Comment by YoshiokaHikari** [comment]
> 我也遇到了一样的问题，Github 登录显示 {"statusCode":500,"message":"Internal server error"}。

用 Railway 部署也是一样的报错

**Comment by xkrfer** [comment]
@YoshiokaHikari github的配置是没问题的吗？

**Comment by xkrfer** [comment]
@YoshiokaHikari 不介意的话，可以把配置email我一份

**Comment by YoshiokaHikari** [comment]
> @YoshiokaHikari 不介意的话，可以把配置email我一份

我要怎么联系你？

**Comment by xkrfer** [comment]
@YoshiokaHikari 邮箱是这个：xkrfer@gmail.com；

**Comment by YoshiokaHikari** [comment]
> @YoshiokaHikari 邮箱是这个：[xkrfer@gmail.com](mailto:xkrfer@gmail.com)；

邮件已发送

**Comment by xkrfer** [comment]
@YoshiokaHikari  endpoint 地址后面不要带上 /，比如endpoint地址是https://a.b.c，那千万不要复制成https://a.b.c/，这部分的逻辑我之后处理一下。
我刚刚用你的地址已经登录成功了😂 

![image](https://user-images.githubusercontent.com/97657327/170977188-9bb577aa-2aa7-4745-a7a0-931521e67976.png)

**Comment by YoshiokaHikari** [comment]
> @YoshiokaHikari endpoint 地址后面不要带上 /，比如endpoint地址是[https://a.b.c，那千万不要复制成https://a.b.c/，这部分的逻辑我之后处理一下。](https://a.b.c%EF%BC%8C%E9%82%A3%E5%8D%83%E4%B8%87%E4%B8%8D%E8%A6%81%E5%A4%8D%E5%88%B6%E6%88%90https://a.b.c/%EF%BC%8C%E8%BF%99%E9%83%A8%E5%88%86%E7%9A%84%E9%80%BB%E8%BE%91%E6%88%91%E4%B9%8B%E5%90%8E%E5%A4%84%E7%90%86%E4%B8%80%E4%B8%8B%E3%80%82) 我刚刚用你的地址已经登录成功了😂
> 
> ![image](https://user-images.githubusercontent.com/97657327/170977188-9bb577aa-2aa7-4745-a7a0-931521e67976.png)

我这里也是没有加 /，有跳转到 Github 认证，但还是出现了上面的错误。用 EDGE 和 Chrome 都是一样的错误。
![image](https://user-images.githubusercontent.com/75349642/170979530-096be1a2-003c-493f-84a4-3d6e4cd8ff73.png)

**Comment by YoshiokaHikari** [comment]
@xkrfer 我这里也是没有加 /，会跳转到 Github 验证，但还是出现上面一样的问题，Edge 和 Chrome 都一样。
![image](https://user-images.githubusercontent.com/75349642/170979962-bd435a8a-5bcc-4a11-9cd1-9fad3ad18af3.png)

**Comment by xkrfer** [comment]
@YoshiokaHikari 在Railway看下日志
![image](https://user-images.githubusercontent.com/97657327/170981354-abde87d4-b176-4bbb-b8ab-21e40a2a8f36.png)
![image](https://user-images.githubusercontent.com/97657327/170981395-1cd161a6-0bb7-4f10-935e-407a7a9a171e.png)

**Comment by somuc** [comment]
应该跟最后面的 /  没关系，我也没有  /

**Comment by xkrfer** [comment]
@somuc 昨天的老哥是因为未设置github用户名的原因导致程序报错了，昨晚已经修复了这个问题，docker镜像已同步更新😂

**Comment by somuc** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    哪里配置github用户名， 我应该也是这个错误
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                974201083
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2022年5月31日 ***@***.***> 写道： 




@somuc 昨天的老哥是因为未设置github用户名的原因导致程序报错了，昨晚已经修复了这个问题，docker镜像已同步更新😂



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by xkrfer** [comment]
@somuc 在这里自定义 https://github.com/settings/profile 
![image](https://user-images.githubusercontent.com/97657327/171099743-c6ac4caa-2bd5-470f-b34b-93a17c2fa693.png)

**Comment by somuc** [comment]
> @somuc 在这里自定义 https://github.com/settings/profile ![image](https://user-images.githubusercontent.com/97657327/171099743-c6ac4caa-2bd5-470f-b34b-93a17c2fa693.png)

/login/github?code=xxx      设置了name，接口还是500错误

**Comment by xkrfer** [comment]
@somuc 方便的话可以把 github 应用的配置以及你部署的地址，同时还有启动日志截图发到这个邮箱 xkrfer@gmail.com

**Comment by somuc** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        我是直接安装在浏览器里了，         endpoint应该不会填错， token失效该怎么处理？
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                974201083
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2022年5月27日 ***@***.***> 写道： 



你是在本地启动pushdeer-crx测试，还是直接装在浏览器里安装扩展使用？

在本地的话无法通过github登录自动登录，需要在登录成功页打开控制台查看登录成功后得到token再填入pushdeer-crx项目中进行使用。


2. 已经使用浏览器插件的话，请检查endpoint是否填入正确，上图的错误提示只有未登录或token失效的情况才会出现。

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
